[loggers]

keys=root, pydeepzoom, error

[handlers]
keys=consoleHandler, pydeepzoom_filelog, error_filelog

[formatters]
keys=simple

[logger_root]
level = INFO
handlers=consoleHandler

[logger_pydeepzoom]
level = ERROR
handlers = pydeepzoom_filelog, consoleHandler
qualname = pydeepzoom
propagate = 1

[logger_error]
level = ERROR
handlers = error_filelog, consoleHandler
qualname = error
propagate = 1

[handler_consoleHandler]
class=StreamHandler
formatter=simple
args=(sys.stdout,)

[handler_pydeepzoom_filelog]
class = FileHandler
formatter = simple
args = ('./logs/pydeepzoom.log',)

[handler_error_filelog]
class = FileHandler
formatter = simple
args = ('./logs/error.log',)


[formatter_simple]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=
